version: "3"
services:
  web:
    build: ./ApiGateway
    network_mode: host
    volumes:
        - "/machine_config:/app/machine_config"
    depends_on: 
      - consul
      - registrator
  consul:
    image: consul
    restart: always
    network_mode: host
  registrator:
    image: gliderlabs/registrator:master
    depends_on:
      - consul
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://0.0.0.0:8500
